//
//  CompanyProfilePage1EditStyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component1437View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		alignSelf: "stretch",
		height: 45,
		marginLeft: 1,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	icForum24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	companyNameText: {
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginTop: 47,
	},
	mainContact1Text: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	textText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 17,
	},
	lineView: {
		backgroundColor: "rgb(226, 232, 237)",
		width: 317,
		height: 1,
	},
	mainContact2Text: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	textTwoText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 17,
	},
	lineTwoView: {
		backgroundColor: "rgb(226, 232, 237)",
		width: 317,
		height: 1,
	},
	cityText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	loremIpsumText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 17,
	},
	lineThreeView: {
		backgroundColor: "rgb(226, 232, 237)",
		width: 317,
		height: 1,
	},
	loremIpsumTwoText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		marginLeft: 31,
		marginTop: 44,
	},
	lineFourView: {
		backgroundColor: "rgb(226, 232, 237)",
		width: 317,
		height: 1,
	},
	zipText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	loremIpsumThreeText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 17,
	},
	lineFiveView: {
		backgroundColor: "rgb(226, 232, 237)",
		width: 317,
		height: 1,
	},
	phoneText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	textThreeText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 17,
	},
	lineSixView: {
		backgroundColor: "rgb(226, 232, 237)",
		width: 317,
		height: 1,
	},
	emailText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		bottom: 23,
	},
	someoneExampleComText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		bottom: 0,
	},
	lineSevenView: {
		backgroundColor: "rgb(226, 232, 237)",
		width: 317,
		height: 1,
		marginBottom: 61,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		position: "absolute",
		left: 1,
		right: 0,
		bottom: 0,
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
	rectangle5View: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 43,
		height: 57,
	},
	saveChangesText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		position: "absolute",
		alignSelf: "center",
		bottom: 58,
	},
	stateText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 30,
	},
})

export default styles
