//
//  ModelSignUp2StyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
		alignItems: "flex-start",
	},
	rectangle2009View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 45,
	},
	myArrowImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 21,
		height: 17,
		marginTop: 2,
	},
	modellyticsLogo300Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 15,
		height: 19,
		marginRight: 6,
		marginTop: 1,
	},
	modellyticsText: {
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	demographicInformatText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 30,
		marginTop: 118,
	},
	birthdayDateText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 30,
		marginTop: 7,
	},
	rectangle14View: {
		backgroundColor: "white",
		borderRadius: 16,
		shadowColor: "rgba(0, 0, 0, 0.09)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 79,
		top: 0,
		height: 32,
	},
	dateText: {
		backgroundColor: "transparent",
		color: "rgb(74, 74, 74)",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	myArrowTwoImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 10,
		height: 5,
		marginLeft: 5,
		marginTop: 7,
	},
	rectangle21View: {
		backgroundColor: "white",
		borderRadius: 16,
		shadowColor: "rgba(0, 0, 0, 0.09)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 100,
		top: 0,
		height: 32,
	},
	monthText: {
		color: "rgb(74, 74, 74)",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	myArrowThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 10,
		height: 5,
		marginTop: 7,
	},
	rectangle22View: {
		backgroundColor: "white",
		borderRadius: 16,
		shadowColor: "rgba(0, 0, 0, 0.09)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 107,
		top: 0,
		height: 32,
	},
	yearText: {
		color: "rgb(74, 74, 74)",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginRight: 6,
	},
	myArrowFourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 10,
		height: 5,
		marginTop: 7,
	},
	ethnicityText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	loremIpsumText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 17,
	},
	lineView: {
		backgroundColor: "rgb(226, 232, 237)",
		alignSelf: "center",
		width: 317,
		height: 1,
	},
	heightText: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 30,
		marginTop: 27,
	},
	rectangle2014View: {
		backgroundColor: "rgb(188, 197, 211)",
		borderRadius: 16,
		shadowColor: "rgba(0, 0, 0, 0.09)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 79,
		top: 0,
		height: 32,
	},
	textFourText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 36,
		top: 6,
	},
	ftText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 9,
		marginTop: 6,
	},
	rectangle2015View: {
		backgroundColor: "rgb(188, 197, 211)",
		borderRadius: 16,
		shadowColor: "rgba(0, 0, 0, 0.09)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 79,
		top: 0,
		height: 32,
	},
	textFiveText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		right: 32,
		top: 6,
	},
	inchesText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginTop: 6,
	},
	weightRangeText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 30,
		marginTop: 22,
	},
	group6View: {
		backgroundColor: "transparent",
		alignSelf: "center",
		width: 190,
		height: 25,
		marginTop: 11,
	},
	rectangle72View: {
		backgroundColor: "rgb(239, 239, 239)",
		borderRadius: 1.5,
		position: "absolute",
		left: 0,
		right: 0,
		top: 14,
		height: 3,
	},
	textText: {
		backgroundColor: "transparent",
		color: "rgb(74, 74, 74)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	rectangle73View: {
		backgroundColor: "rgb(76, 82, 100)",
		borderRadius: 1.5,
		width: 61,
		height: 3,
		marginRight: 23,
		marginTop: 14,
	},
	textTwoText: {
		color: "rgb(74, 74, 74)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "right",
		backgroundColor: "transparent",
	},
	ellipse44View: {
		backgroundColor: "rgb(76, 82, 100)",
		borderRadius: 9,
		width: 18,
		height: 18,
	},
	ellipse32View: {
		backgroundColor: "rgb(76, 82, 100)",
		borderRadius: 9,
		width: 18,
		height: 18,
	},
	textThreeText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-end",
		marginRight: 154,
		marginTop: 16,
	},
	rectangle5View: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 57,
	},
	nextText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		position: "absolute",
		alignSelf: "center",
		bottom: 15,
	},
	alreadyAMemberSText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		alignSelf: "center",
		marginBottom: 1,
	},
	copyright2015201Text: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		alignSelf: "center",
		marginBottom: 15,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		alignSelf: "stretch",
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
})

export default styles
