//
//  CompanyProfilePage1StyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component1436View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		marginTop: 44,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	icForum24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	слои1Image: {
		backgroundColor: "transparent",
		resizeMode: "cover",
		alignSelf: "center",
		width: 292,
		height: 128,
		marginTop: 43,
	},
	companyNameText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "center",
		marginTop: 10,
	},
	rectangle2090View: {
		backgroundColor: "rgb(246, 246, 246)",
		borderRadius: 8,
		position: "absolute",
		alignSelf: "center",
		width: 287,
		top: 0,
		height: 372,
	},
	ellipse109View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 9,
		width: 18,
		height: 18,
		marginTop: 2,
	},
	mainContactText: {
		color: "rgb(88, 135, 249)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 7,
	},
	textText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 26,
		marginTop: 2,
	},
	cityText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 10,
		marginTop: 32,
	},
	stateText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 10,
		marginTop: 30,
	},
	zipText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 10,
		marginTop: 30,
	},
	ellipse110View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 9,
		width: 18,
		height: 18,
		marginTop: 2,
	},
	phoneText: {
		color: "rgb(88, 135, 249)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 7,
	},
	textTwoText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 1,
		marginTop: 2,
	},
	group589Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 19,
		height: 14,
		marginBottom: 8,
	},
	emailText: {
		color: "rgb(88, 135, 249)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 5,
	},
	someoneExampleComText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 2,
	},
	group588Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 10,
		height: 10,
	},
	group588TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 10,
		height: 10,
		marginTop: 223,
	},
	textThreeText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 41,
		top: 63,
	},
	loremIpsumText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	loremIpsumTwoText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginTop: 24,
	},
	loremIpsumThreeText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginTop: 24,
	},
	rectangle7View: {
		backgroundColor: "transparent",
		borderWidth: 2,
		borderColor: "rgb(76, 82, 100)",
		borderStyle: "solid",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		alignSelf: "center",
		width: 305,
		bottom: 0,
		height: 57,
	},
	editImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 20,
		height: 20,
		marginBottom: 4,
	},
	editInformationText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	homeIndicatorView: {
		backgroundColor: "white",
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
})

export default styles
