//
//  MobileBlogPageStyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component1441View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		marginTop: 44,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	icForum24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	nopathCopy16Image: {
		resizeMode: "cover",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 363,
	},
	myArrowImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.28,
		width: 8,
		height: 13,
	},
	myArrowTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.28,
		width: 11,
		height: 11,
		marginTop: 2,
	},
	july12020Text: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 0,
	},
	areYouWorkingInAText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 17,
	},
	loremIpsumDolorSiText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-end",
		width: 326,
		marginRight: 19,
		marginBottom: 64,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
	textText: {
		backgroundColor: "transparent",
		color: "rgb(88, 135, 249)",
		fontFamily: "Poppins-Regular",
		fontSize: 44,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginBottom: 13,
	},
	loremIpsumDolorSiTwoText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		paddingTop: 1,
		width: 279,
	},
	textTwoText: {
		backgroundColor: "transparent",
		color: "rgb(88, 135, 249)",
		fontFamily: "Poppins-Regular",
		fontSize: 44,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 171,
		bottom: 10,
	},
})

export default styles
