//
//  AdminDashboardSwipeRight1StyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component143View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		marginTop: 44,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	icForum24pxImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	group14View: {
		backgroundColor: "transparent",
		alignSelf: "flex-end",
		width: 614,
		height: 147,
		marginTop: 60,
	},
	group11View: {
		backgroundColor: "rgb(76, 82, 100)",
		borderRadius: 4,
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		width: 196,
		height: 97,
		flexDirection: "row",
		alignItems: "center",
	},
	group10View: {
		backgroundColor: "white",
		borderRadius: 23,
		width: 46,
		height: 46,
		marginLeft: 16,
		justifyContent: "center",
	},
	icAssignment24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 22,
		marginLeft: 12,
		marginRight: 13,
	},
	createJobText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		marginRight: 15,
		marginTop: 36,
	},
	group13View: {
		backgroundColor: "transparent",
		borderRadius: 4,
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		width: 196,
		height: 147,
		flexDirection: "row",
		alignItems: "center",
	},
	group10TwoView: {
		backgroundColor: "white",
		borderRadius: 23,
		width: 46,
		height: 46,
		marginLeft: 28,
		justifyContent: "center",
	},
	editImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 25,
		marginLeft: 11,
		marginRight: 10,
	},
	editJobsText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		marginRight: 25,
		marginTop: 61,
	},
	group12View: {
		backgroundColor: "rgb(76, 82, 100)",
		borderRadius: 4,
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		width: 196,
		height: 97,
		flexDirection: "row",
		alignItems: "center",
	},
	group10ThreeView: {
		backgroundColor: "white",
		borderRadius: 23,
		width: 46,
		height: 46,
		marginLeft: 21,
		justifyContent: "center",
	},
	icAccountBalanceWImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 19,
		marginLeft: 12,
		marginRight: 12,
	},
	viewJobsText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-start",
		marginRight: 20,
		marginTop: 36,
	},
	group17View: {
		backgroundColor: "rgb(243, 243, 243)",
		position: "absolute",
		left: 0,
		width: 189,
		top: 0,
		height: 204,
		justifyContent: "center",
		alignItems: "flex-start",
	},
	group16View: {
		backgroundColor: "transparent",
		width: 121,
		height: 69,
		marginLeft: 30,
		alignItems: "center",
	},
	icAccountBox24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 40,
		height: 38,
	},
	viewApplicantsText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "stretch",
	},
	group18View: {
		backgroundColor: "rgb(243, 243, 243)",
		position: "absolute",
		right: 0,
		width: 189,
		top: 0,
		height: 204,
		alignItems: "center",
	},
	icChromeReaderModImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 52,
		height: 39,
		marginTop: 69,
	},
	companyProfileText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		marginTop: 6,
	},
	rectangle2023View: {
		backgroundColor: "rgb(206, 206, 206)",
		borderRadius: 1,
		position: "absolute",
		alignSelf: "center",
		width: 2,
		top: 25,
		height: 154,
	},
	rectangle2022View: {
		backgroundColor: "rgb(76, 82, 100)",
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 119,
	},
	icSettings24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 40,
		height: 39,
	},
	settingsText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	homeIndicatorView: {
		backgroundColor: "white",
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
})

export default styles
