//
//  ViewApplicantsPage3StyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component1431View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	icForum24pxImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	myArrowImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.28,
		width: 8,
		height: 13,
	},
	myArrowTwoImage: {
		backgroundColor: "transparent",
		opacity: 0.28,
		resizeMode: "center",
		width: 11,
		height: 11,
		marginTop: 2,
	},
	jobOneText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "center",
		marginTop: 17,
	},
	rectangle2056View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 113,
		top: 0,
		height: 162,
	},
	rectangle2057Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 113,
		height: 126,
	},
	avidloveText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 6,
		marginTop: 6,
	},
	ellipse77View: {
		backgroundColor: "black",
		opacity: 0.09,
		borderRadius: 18.5,
		width: 37,
		height: 37,
		marginLeft: 65,
	},
	шубаИзМехаНоркиText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginTop: 1,
	},
	ellipse78View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 18.5,
		position: "absolute",
		left: 70,
		width: 37,
		top: 107,
		height: 37,
	},
	textText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 7,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 76,
		top: 119,
	},
	рублеиText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 5,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 80,
		top: 128,
	},
	avidloveFourText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 11,
		marginTop: 132,
	},
	ellipse79View: {
		backgroundColor: "black",
		opacity: 0.09,
		borderRadius: 18.5,
		position: "absolute",
		right: 0,
		width: 37,
		top: 1,
		height: 37,
	},
	ellipse80View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 18.5,
		position: "absolute",
		right: 1,
		width: 37,
		top: 0,
		height: 37,
	},
	textFourText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 7,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		right: 4,
		top: 12,
	},
	рублеиFourText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 5,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		right: 10,
		top: 21,
	},
	rectangle2060View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 113,
		top: 0,
		height: 162,
	},
	rectangle2061Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 126,
	},
	avidloveSevenText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginRight: 45,
		marginTop: 6,
	},
	ellipse81View: {
		backgroundColor: "black",
		opacity: 0.09,
		borderRadius: 18.5,
		width: 37,
		height: 37,
	},
	шубаИзМехаНоркиSevenText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginRight: 2,
		marginTop: 1,
	},
	ellipse82View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 18.5,
		position: "absolute",
		right: 6,
		width: 37,
		top: 107,
		height: 37,
	},
	textSevenText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 7,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		right: 9,
		top: 119,
	},
	рублеиSevenText: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 5,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		right: 15,
		top: 128,
	},
	rectangle2066View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 113,
		top: 0,
		height: 162,
	},
	rectangle2067Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 126,
	},
	avidloveTwoText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 6,
		marginTop: 6,
	},
	ellipse87View: {
		backgroundColor: "black",
		opacity: 0.09,
		borderRadius: 18.5,
		width: 37,
		height: 37,
		marginLeft: 65,
	},
	шубаИзМехаНоркиTwoText: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginTop: 1,
	},
	ellipse88View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 18.5,
		position: "absolute",
		left: 70,
		width: 37,
		top: 107,
		height: 37,
	},
	textTwoText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 7,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 76,
		top: 119,
	},
	рублеиTwoText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 5,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 80,
		top: 128,
	},
	avidloveFiveText: {
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 11,
		marginTop: 132,
	},
	ellipse85View: {
		backgroundColor: "black",
		opacity: 0.09,
		borderRadius: 18.5,
		position: "absolute",
		right: 0,
		width: 37,
		top: 1,
		height: 37,
	},
	ellipse86View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 18.5,
		position: "absolute",
		right: 1,
		width: 37,
		top: 0,
		height: 37,
	},
	textFiveText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 7,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		right: 4,
		top: 12,
	},
	рублеиFiveText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 5,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		right: 10,
		top: 21,
	},
	rectangle2062View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 113,
		top: 0,
		height: 162,
	},
	rectangle2063Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 126,
	},
	avidloveEightText: {
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginRight: 45,
		marginTop: 6,
	},
	ellipse84View: {
		backgroundColor: "black",
		opacity: 0.09,
		borderRadius: 18.5,
		width: 37,
		height: 37,
	},
	шубаИзМехаНоркиEightText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginRight: 2,
		marginTop: 1,
	},
	ellipse83View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 18.5,
		position: "absolute",
		right: 6,
		width: 37,
		top: 107,
		height: 37,
	},
	textEightText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 7,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		right: 9,
		top: 119,
	},
	рублеиEightText: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 5,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		right: 15,
		top: 128,
	},
	rectangle2072View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 113,
		bottom: 1,
		height: 162,
	},
	rectangle2073Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 126,
		marginBottom: 6,
	},
	avidloveThreeText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 6,
	},
	ellipse93View: {
		backgroundColor: "black",
		opacity: 0.09,
		borderRadius: 18.5,
		width: 37,
		height: 37,
		marginLeft: 65,
		marginBottom: 1,
	},
	шубаИзМехаНоркиThreeText: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	ellipse94View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 18.5,
		position: "absolute",
		left: 70,
		width: 37,
		bottom: 19,
		height: 37,
	},
	textThreeText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 7,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 76,
		bottom: 34,
	},
	рублеиThreeText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 5,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 80,
		bottom: 29,
	},
	avidloveSixText: {
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 11,
		marginBottom: 10,
	},
	ellipse91View: {
		backgroundColor: "black",
		opacity: 0.09,
		borderRadius: 18.5,
		position: "absolute",
		right: 0,
		width: 37,
		bottom: 0,
		height: 37,
	},
	ellipse92View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 18.5,
		position: "absolute",
		right: 1,
		width: 37,
		bottom: 1,
		height: 37,
	},
	textSixText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 7,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		right: 4,
		bottom: 16,
	},
	рублеиSixText: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 5,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		right: 10,
		bottom: 11,
	},
	rectangle2068View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 113,
		bottom: 1,
		height: 162,
	},
	rectangle2069Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 113,
		height: 126,
		marginBottom: 6,
	},
	avidloveNineText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginRight: 45,
	},
	ellipse90View: {
		backgroundColor: "black",
		opacity: 0.09,
		borderRadius: 18.5,
		width: 37,
		height: 37,
		marginBottom: 1,
	},
	шубаИзМехаНоркиNineText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginRight: 2,
	},
	ellipse89View: {
		backgroundColor: "rgb(88, 135, 249)",
		borderRadius: 18.5,
		position: "absolute",
		right: 6,
		width: 37,
		bottom: 19,
		height: 37,
	},
	textNineText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 7,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		right: 9,
		bottom: 34,
	},
	рублеиNineText: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 5,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		right: 15,
		bottom: 29,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
	projectInformationText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	rectangle2058View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 162,
		marginTop: 46,
	},
	rectangle2064View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 162,
		marginTop: 15,
	},
	rectangle2070View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 162,
	},
	rectangle2059Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 126,
	},
	шубаИзМехаНоркиFourText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginTop: 20,
	},
	rectangle2065Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 126,
		marginTop: 14,
	},
	шубаИзМехаНоркиFiveText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginTop: 20,
	},
	rectangle2071Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 5,
		shadowOpacity: 1,
		width: 113,
		height: 126,
		marginBottom: 20,
	},
	шубаИзМехаНоркиSixText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
})

export default styles
