//
//  CreateJobPage2StyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component145View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		marginLeft: 1,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	icForum24pxImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	myArrowFiveImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.28,
		width: 8,
		height: 13,
	},
	myArrowSixImage: {
		backgroundColor: "transparent",
		opacity: 0.28,
		resizeMode: "center",
		width: 11,
		height: 11,
		marginTop: 2,
	},
	step2Text: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		alignSelf: "center",
		marginTop: 15,
	},
	categoryText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	listEntry1Text: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 17,
	},
	lineView: {
		backgroundColor: "rgb(226, 232, 237)",
		alignSelf: "center",
		width: 308,
		height: 1,
	},
	approxJobLengthText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	listEntry1TwoText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 17,
	},
	myArrowTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 13,
		height: 8,
		marginRight: 5,
		marginTop: 23,
	},
	circleTwoView: {
		backgroundColor: "transparent",
		width: 19,
		height: 19,
		marginTop: 17,
	},
	group531TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 19,
	},
	group535TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		left: 8,
		right: 8,
		bottom: 3,
		height: 2,
	},
	group533TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 9,
		marginLeft: 8,
		marginRight: 8,
	},
	lineTwoView: {
		backgroundColor: "rgb(226, 232, 237)",
		alignSelf: "center",
		width: 308,
		height: 1,
	},
	experienceLevelText: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 0,
	},
	listEntry1ThreeText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 17,
	},
	myArrowThreeImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 13,
		height: 8,
		marginRight: 5,
		marginTop: 23,
	},
	circleThreeView: {
		backgroundColor: "transparent",
		width: 19,
		height: 19,
		marginTop: 17,
	},
	group531ThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 19,
	},
	group535ThreeImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		position: "absolute",
		left: 8,
		right: 8,
		bottom: 3,
		height: 2,
	},
	group533ThreeImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 9,
		marginLeft: 8,
		marginRight: 8,
	},
	lineThreeView: {
		backgroundColor: "rgb(226, 232, 237)",
		alignSelf: "center",
		width: 308,
		height: 1,
	},
	salaryText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	listEntry1FourText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 17,
	},
	myArrowFourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 13,
		height: 8,
		marginRight: 5,
		marginTop: 23,
	},
	circleFourView: {
		backgroundColor: "transparent",
		width: 19,
		height: 19,
		marginTop: 17,
	},
	group531FourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 19,
	},
	group535FourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		left: 8,
		right: 8,
		bottom: 3,
		height: 2,
	},
	group533FourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 9,
		marginLeft: 8,
		marginRight: 8,
	},
	lineFourView: {
		backgroundColor: "rgb(226, 232, 237)",
		alignSelf: "center",
		width: 308,
		height: 1,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		position: "absolute",
		left: 1,
		right: 0,
		bottom: 0,
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
	rectangle5View: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 43,
		height: 57,
	},
	nextText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		alignSelf: "center",
		bottom: 58,
	},
	projectInformationText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		position: "absolute",
		alignSelf: "center",
		top: 139,
	},
})

export default styles
