//
//  PhotosChoose1StyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component1421View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		marginLeft: 1,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	icForum24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	rectangle2040Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 123,
		height: 123,
	},
	rectangle2042Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 123,
		height: 123,
	},
	rectangle2043Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 123,
		height: 123,
	},
	rectangle2045Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 123,
		height: 123,
	},
	rectangle2049Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 123,
		height: 123,
	},
	rectangle2051Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 123,
		height: 123,
	},
	rectangle2046Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 123,
		top: 0,
		height: 123,
	},
	rectangle2055View: {
		backgroundColor: "rgb(88, 130, 232)",
		opacity: 0.85,
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		width: 123,
		top: 0,
		height: 123,
	},
	group544TwoImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		position: "absolute",
		left: 48,
		width: 26,
		top: 51,
		height: 20,
	},
	rectangle2048Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 123,
		height: 123,
	},
	rectangle2052Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 123,
		height: 123,
	},
	rectangle2054Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 123,
		height: 123,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
	rectangle5View: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 43,
		height: 57,
	},
	ellipse47View: {
		backgroundColor: "white",
		borderRadius: 11,
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 131,
		width: 22,
		bottom: 61,
		height: 22,
	},
	textText: {
		backgroundColor: "transparent",
		color: "rgb(96, 189, 255)",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		right: 137,
		bottom: 59,
	},
	rectangle2041Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 123,
		height: 123,
	},
	rectangle2044Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 123,
		height: 123,
		marginTop: 2,
	},
	rectangle2050Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 123,
		height: 123,
		marginTop: 2,
	},
	rectangle2047Image: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		resizeMode: "center",
		width: 123,
		height: 123,
		marginTop: 2,
	},
	rectangle2053Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		width: 123,
		height: 123,
		marginBottom: 10,
	},
	selectText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	rectangle2044View: {
		backgroundColor: "rgb(88, 130, 232)",
		opacity: 0.85,
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 2,
		shadowOpacity: 1,
		position: "absolute",
		alignSelf: "center",
		width: 123,
		top: 223,
		height: 123,
	},
	group544Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		alignSelf: "center",
		width: 26,
		top: 274,
		height: 20,
	},
})

export default styles
