//
//  ContactUsStyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component1444View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		marginTop: 44,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	icForum24pxImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	nopathCopy19Image: {
		resizeMode: "cover",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 145,
	},
	nopathCopy17View: {
		backgroundColor: "black",
		opacity: 0.64,
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 145,
	},
	myArrowImage: {
		backgroundColor: "transparent",
		opacity: 0.28,
		resizeMode: "center",
		width: 8,
		height: 13,
	},
	myArrowTwoImage: {
		backgroundColor: "transparent",
		opacity: 0.28,
		resizeMode: "center",
		width: 11,
		height: 11,
		marginTop: 2,
	},
	contactUsText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-start",
		marginLeft: 21,
		marginTop: 12,
	},
	rectangle2092View: {
		backgroundColor: "rgb(245, 245, 245)",
		borderRadius: 17,
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		width: 331,
		height: 179,
		marginTop: 6,
	},
	group604Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 28,
		height: 21,
	},
	someoneExampleComText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	group606Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 21,
		height: 21,
	},
	textText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 15,
		marginTop: 2,
	},
	globeImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 26,
		height: 26,
	},
	wwwMywebsiteComText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 12,
		marginTop: 1,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
})

export default styles
