//
//  UserDashboardStyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
		alignItems: "flex-start",
	},
	component1445View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		alignSelf: "stretch",
		height: 45,
		marginTop: 44,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	icForum24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	ellipse2Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		alignSelf: "center",
		width: 121,
		top: 0,
		height: 122,
	},
	ellipse3Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		right: 0,
		width: 35,
		top: 81,
		height: 36,
	},
	group4Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		position: "absolute",
		right: 10,
		width: 16,
		top: 92,
		height: 14,
	},
	userInformationText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 36,
		marginTop: 39,
	},
	aaronSmithText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 17,
	},
	usernameText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	lineView: {
		backgroundColor: "rgb(226, 232, 237)",
		alignSelf: "center",
		width: 317,
		height: 1,
	},
	someoneExampleComText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 17,
	},
	emailText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	lineTwoView: {
		backgroundColor: "rgb(226, 232, 237)",
		alignSelf: "center",
		width: 317,
		height: 1,
	},
	textText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 17,
	},
	passwordText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	lineThreeView: {
		backgroundColor: "rgb(226, 232, 237)",
		alignSelf: "center",
		width: 317,
		height: 1,
	},
	textTwoText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 17,
	},
	confirmPasswordText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		top: 0,
	},
	lineFourView: {
		backgroundColor: "rgb(226, 232, 237)",
		alignSelf: "center",
		width: 317,
		height: 1,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		position: "absolute",
		left: 1,
		right: 0,
		bottom: 0,
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
	rectangle5View: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 43,
		height: 57,
	},
	saveChangesText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		position: "absolute",
		alignSelf: "center",
		bottom: 58,
	},
})

export default styles
