//
//  Chat1StyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
		alignItems: "flex-start",
	},
	group110View: {
		backgroundColor: "rgb(249, 249, 249)",
		position: "absolute",
		left: 13,
		right: 13,
		top: 6,
		height: 48,
		flexDirection: "row",
		alignItems: "flex-start",
	},
	phoneVideoText: {
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 11,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		marginLeft: 21,
		marginTop: 21,
	},
	groupVideoText: {
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 11,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		marginLeft: 27,
		marginTop: 21,
	},
	liveVideoText: {
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		marginRight: 25,
		marginTop: 21,
	},
	group43View: {
		backgroundColor: "transparent",
		width: 16,
		height: 18,
		marginRight: 5,
		marginTop: 19,
	},
	filmImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 10,
	},
	rectangle45View: {
		backgroundColor: "rgb(26, 26, 26)",
		borderRadius: 1,
		shadowColor: "rgba(0, 0, 0, 0.25)",
		shadowRadius: 0,
		shadowOpacity: 1,
		height: 18,
		marginLeft: 7,
		marginRight: 6,
	},
	rectangle58View: {
		backgroundColor: "white",
		width: 1,
		height: 20,
		marginRight: 4,
		marginTop: 18,
	},
	filmTwoImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 18,
		height: 11,
		marginRight: 18,
		marginTop: 23,
	},
	rectangle31View: {
		backgroundColor: "rgb(249, 249, 249)",
		shadowColor: "rgba(0, 0, 0, 0.1)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		top: 0,
		height: 54,
	},
	group23Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 8,
		height: 14,
		marginTop: 11,
	},
	alexSemeulText: {
		color: "rgb(99, 149, 249)",
		fontFamily: "Roboto-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		marginLeft: 56,
		marginTop: 2,
	},
	group32Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 34,
		height: 35,
	},
	rectangle32View: {
		backgroundColor: "rgb(76, 82, 100)",
		borderRadius: 17,
		position: "absolute",
		right: 0,
		width: 102,
		top: 0,
		height: 34,
	},
	helloJohnText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		position: "absolute",
		right: 12,
		top: 9,
	},
	rectangle33View: {
		backgroundColor: "rgb(76, 82, 100)",
		borderRadius: 17,
		position: "absolute",
		right: 0,
		width: 191,
		top: 0,
		height: 34,
	},
	iSeeYouAreFromSText: {
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "right",
		backgroundColor: "transparent",
		position: "absolute",
		right: 7,
		top: 9,
	},
	rectangle34View: {
		backgroundColor: "rgb(76, 82, 100)",
		borderRadius: 17,
		position: "absolute",
		right: 0,
		width: 160,
		top: 0,
		height: 34,
	},
	upForAVideoChatText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "right",
		position: "absolute",
		right: 13,
		top: 9,
	},
	helloThereText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 76,
		marginTop: 49,
	},
	iMWalkingHomeText: {
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 76,
		marginTop: 17,
	},
	group599Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 34,
		height: 35,
	},
	catchYouBackIn5Text: {
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 21,
		marginTop: 10,
	},
	rectangle40View: {
		backgroundColor: "rgb(76, 82, 100)",
		borderRadius: 17,
		position: "absolute",
		right: 0,
		width: 122,
		top: 0,
		height: 34,
	},
	sureBeSafeText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Roboto-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "right",
		position: "absolute",
		right: 13,
		top: 9,
	},
	group600Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 34,
		height: 35,
		marginLeft: 21,
		marginBottom: 42,
	},
	rectangle29View: {
		backgroundColor: "rgb(249, 249, 249)",
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 0,
		height: 46,
	},
	rectangle30View: {
		backgroundColor: "white",
		borderRadius: 17,
		shadowColor: "rgba(0, 0, 0, 0.06)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 18,
		right: 20,
		bottom: 7,
		height: 34,
	},
	typeHereText: {
		backgroundColor: "transparent",
		color: "rgb(164, 164, 164)",
		fontFamily: "Roboto-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		marginBottom: 1,
	},
	smilingImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 22,
		height: 22,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		alignSelf: "stretch",
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
})

export default styles
