//
//  ViewApplicantsPage3ScrollStyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component1433View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		marginLeft: 78,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	icForum24pxImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	myArrowImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.28,
		width: 8,
		height: 13,
	},
	myArrowTwoImage: {
		backgroundColor: "transparent",
		opacity: 0.28,
		resizeMode: "center",
		width: 11,
		height: 11,
		marginTop: 2,
	},
	jobOneText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "center",
		marginTop: 17,
	},
	nopathCopy15Image: {
		backgroundColor: "transparent",
		resizeMode: "cover",
		position: "absolute",
		left: 78,
		right: 0,
		top: 0,
		height: 505,
	},
	nopathCopy14Image: {
		backgroundColor: "transparent",
		resizeMode: "cover",
		position: "absolute",
		left: 78,
		right: 0,
		top: 0,
		height: 505,
	},
	nopathCopy3Image: {
		backgroundColor: "transparent",
		resizeMode: "cover",
		position: "absolute",
		left: 90,
		right: 12,
		top: 16,
		height: 473,
	},
	icChevronRight24pImage: {
		backgroundColor: "transparent",
		opacity: 0.93,
		resizeMode: "center",
		width: 8,
		height: 13,
	},
	icChevronRight24pTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.93,
		width: 8,
		height: 13,
	},
	rectangle2080View: {
		backgroundColor: "rgb(51, 52, 55)",
		borderRadius: 6,
		alignSelf: "center",
		width: 313,
		height: 66,
		marginTop: 157,
	},
	group587Image: {
		resizeMode: "cover",
		backgroundColor: "transparent",
		position: "absolute",
		left: 0,
		width: 416,
		top: 421,
		height: 56,
	},
	nameText: {
		backgroundColor: "transparent",
		color: "rgb(0, 132, 206)",
		fontFamily: "Poppins-Regular",
		fontSize: 25,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 0,
	},
	descriptionLoremText: {
		color: "rgb(46, 49, 51)",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		paddingTop: 6,
		backgroundColor: "transparent",
		position: "absolute",
		alignSelf: "center",
		width: 323,
		bottom: 17,
	},
	rectangle5View: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		alignSelf: "center",
		width: 323,
		bottom: 0,
		height: 57,
	},
	interestedText: {
		backgroundColor: "transparent",
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		position: "absolute",
		alignSelf: "center",
		bottom: 14,
	},
	projectInformationText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		position: "absolute",
		alignSelf: "center",
		top: 139,
	},
})

export default styles
