//
//  ViewJobsPage1DropDownStyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component1414View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		marginLeft: 1,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	icForum24pxImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	myArrowTwoImage: {
		backgroundColor: "transparent",
		opacity: 0.28,
		resizeMode: "center",
		width: 8,
		height: 13,
	},
	myArrowThreeImage: {
		backgroundColor: "transparent",
		opacity: 0.28,
		resizeMode: "center",
		width: 11,
		height: 11,
		marginTop: 2,
	},
	selectAProjectFroText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		lineHeight: 20,
		alignSelf: "center",
		marginTop: 13,
	},
	projectNameText: {
		backgroundColor: "transparent",
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "flex-start",
		marginLeft: 1,
	},
	myArrowImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		alignSelf: "flex-end",
		width: 13,
		height: 8,
		marginRight: 23,
		marginTop: 4,
	},
	lineView: {
		backgroundColor: "rgb(226, 232, 237)",
		width: 308,
		height: 1,
		marginTop: 11,
	},
	selectAJobFromThText: {
		backgroundColor: "transparent",
		opacity: 0,
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		lineHeight: 20,
		marginTop: 51,
	},
	group543View: {
		backgroundColor: "white",
		borderRadius: 4,
		shadowColor: "rgba(0, 0, 0, 0.16)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 1,
		width: 290,
		top: 14,
		height: 119,
		alignItems: "flex-start",
	},
	listEntry1TwoText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 10,
		marginTop: 5,
	},
	listEntry2Text: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 10,
		marginTop: 5,
	},
	listEntry3Text: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 10,
		marginTop: 1,
	},
	listEntry4Text: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		marginLeft: 10,
		marginBottom: 4,
	},
	jobNamesText: {
		backgroundColor: "transparent",
		opacity: 0,
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		position: "absolute",
		left: 0,
		top: 0,
	},
	rectangle2034View: {
		backgroundColor: "white",
		opacity: 0,
		borderRadius: 4,
		position: "absolute",
		left: 0,
		width: 290,
		top: 14,
		height: 28,
	},
	listEntry1Text: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		opacity: 0,
	},
	myArrowFourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0,
		width: 13,
		height: 8,
		marginRight: 5,
		marginTop: 6,
	},
	circleTwoView: {
		backgroundColor: "transparent",
		opacity: 0,
		width: 19,
		height: 19,
	},
	group531TwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: null,
		height: 19,
	},
	group535TwoImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		position: "absolute",
		left: 8,
		right: 8,
		bottom: 3,
		height: 2,
	},
	group533TwoImage: {
		backgroundColor: "transparent",
		resizeMode: "center",
		width: null,
		height: 9,
		marginLeft: 8,
		marginRight: 8,
	},
	lineTwoView: {
		backgroundColor: "rgb(226, 232, 237)",
		opacity: 0,
		alignSelf: "center",
		width: 308,
		height: 1,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		position: "absolute",
		left: 1,
		right: 0,
		bottom: 0,
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
	rectangle5View: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 43,
		height: 57,
	},
	nextText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		alignSelf: "center",
		bottom: 58,
	},
	projectInformationText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
		position: "absolute",
		alignSelf: "center",
		top: 139,
	},
})

export default styles
