//
//  CreateJobPage3StyleSheet.js
//  EyeQ
//
//  Created by [Author].
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	viewView: {
		backgroundColor: "white",
		flex: 1,
	},
	component146View: {
		backgroundColor: "white",
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6,
		shadowOpacity: 1,
		height: 45,
		marginLeft: 1,
		flexDirection: "row",
		alignItems: "center",
	},
	group15Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 21,
		height: 18,
		marginLeft: 25,
	},
	group9View: {
		backgroundColor: "transparent",
		width: 104,
		height: 20,
		marginLeft: 30,
		flexDirection: "row",
		alignItems: "center",
	},
	modellyticsLogo300Image: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 15,
		height: 19,
	},
	modellyticsText: {
		color: "rgb(76, 82, 100)",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
	},
	icForum24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 25,
		height: 23,
		marginRight: 24,
	},
	myArrowTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		opacity: 0.28,
		width: 8,
		height: 13,
	},
	myArrowThreeImage: {
		backgroundColor: "transparent",
		opacity: 0.28,
		resizeMode: "center",
		width: 11,
		height: 11,
		marginTop: 2,
	},
	step3Text: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		alignSelf: "center",
		marginTop: 15,
	},
	descriptionText: {
		color: "rgb(188, 197, 211)",
		fontFamily: "Poppins-Regular",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		alignSelf: "flex-start",
		marginLeft: 34,
		marginTop: 92,
	},
	loremIpsumDolorSiText: {
		backgroundColor: "transparent",
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		alignSelf: "center",
		width: 275,
		marginTop: 18,
	},
	homeIndicatorView: {
		backgroundColor: "white",
		position: "absolute",
		left: 1,
		right: 0,
		bottom: 0,
		height: 44,
		alignItems: "center",
	},
	homeIndicatorTwoView: {
		backgroundColor: "black",
		opacity: 0.2,
		borderRadius: 2.5,
		width: 134,
		height: 5,
		marginTop: 28,
	},
	rectangle5View: {
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 6,
		shadowOpacity: 1,
		position: "absolute",
		left: 0,
		right: 0,
		bottom: 43,
		height: 57,
	},
	nextText: {
		color: "white",
		fontFamily: "Poppins-Regular",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		position: "absolute",
		alignSelf: "center",
		bottom: 58,
	},
	projectInformationText: {
		color: "rgb(76, 82, 100)",
		fontFamily: "Poppins-Regular",
		fontSize: 20,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	rectangle2029View: {
		backgroundColor: "white",
		borderRadius: 4,
		borderWidth: 1,
		borderColor: "rgb(188, 197, 211)",
		borderStyle: "solid",
		width: 308,
		height: 202,
	},
})

export default styles
